version: "3.8"

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment: 
      POSTGRES_PASSWORD: 102030
      POSTGRES_USER : postgres
      POSTGRES_DB : application_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend-api
    # restart: always
    # working_dir: 
    build:
      context: .
      dockerfile: Backend.Dockerfile
    # image: backend-typescript
    # command: 
    volumes:
      - . :/usr/app
    depends_on: 
      - postgres-db
    links:
      - postgres-db
    ports:
    - "3333:3333"